// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    "intro",
    {
      type: "category",
      label: "🏗️ Architecture",
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "architecture" }],
    },

    {
      type: "category",
      label: "🧩 CRM",
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "crm" }],
    },

    {
      type: "category",
      label: "🏠 Editor",
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "editor" }],
    },

    {
      type: "category",
      label: "⚡ Energy",
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "energy" }],
    },

    {
      type: "category",
      label: "💰 Pricing",
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "pricing" }],
    },

    {
      type: "category",
      label: "📄 Proposal",
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "proposal" }],
    },

    {
      type: "category",
      label: "🔌 API",
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "api" }],
    },

    {
      type: "category",
      label: "🎯 UX & Behavior",
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "ux" }],
    },
  ],
};

export default sidebars;
